### PR TITLE
check if data exists preventing array offset on value of type bool error ✨

### PR DESCRIPTION
**Pull request by mr-pmillz**
This will fix this bug 
```shell
Notice: Trying to access array offset on value of type bool in /MAGENTO_ROOT/vendor/avalara/avatax-magento/Plugin/Model/ResourceModel/ExtensionAttributesPersistencePlugin.php on line 251"
```

### CODE REVIEW

**Comment by marynychsv** [comment]
Hello, 

we have created a ticket for your request.
we keep you posted.

thank you

**Comment by mr-pmillz** [comment]
Sounds good, Thank you

**Comment by aholovan** [comment]
Hi, the same error with 2.2 version on Magento 2.4.1

**Comment by mr-pmillz** [comment]
Any progress with this @marynychsv ?

**Comment by alexbejan-mavfarm** [comment]
It doesn't seem like this is enough, line 237 is also failing, it seems the array keys ($tableName) is an array so the foreach throws an error

```
foreach (array_unique($tablesToUpdate) as $tableName => $tableDirective) {
```

For more info, this is happening when refunding an invoice via the API

**Comment by virtual97** [comment]
Hello,
Looks like the issue is not actual anymore.
Fixed in 2.2.3 version.
MR is closed.
Thanks.

**Pull request closed without merging**
